name: Metrics
on:
  schedule: [{cron: "0 6 */3 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: nzkdevsaider
          template: classic
          base: header, activity, metadata
          config_timezone: America/Panama
          plugin_leetcode: yes
          plugin_leetcode_user: nzkdevsaider
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
